spring:
  profiles:
    active: ${PROFILE:local}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://${DB_ENDPOINT}/calender?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    cors:
      mappings:
        "/api/**":
          allowed-origins: "http://localhost:8080"
          allowed-methods: "GET,POST,PUT,DELETE"
          allow-credentials: true

allowed:
  origins: http://localhost:3000,http://localhost:5500,http://localhost:5173


